time1 = time.time()
single_astar("./lab_a_files/1prize-open.txt")
print(f"Runtime for 1prize-open.txt: {round(time.time() - time1,5)}\n")
time2 = time.time()
single_astar("./lab_a_files/1prize-medium.txt")
print(f"Runtime for 1prize-medium.txt: {round(time.time() - time2,5)}\n")
time3 = time.time()
single_astar("./lab_a_files/1prize-large.txt")
print(f"Runtime for 1prize-large.txt: {round(time.time() - time3,5)}\n")